/**
 * Reads the Foundry artifact and writes a viem-typed ABI subset.
 * Run: pnpm abi:sync
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ARTIFACT = join(
  ROOT,
  "contracts/out/BoardingPass.sol/BoardingPass.json",
);
const OUT = join(ROOT, "app/lib/evm/abi/boardingPass.ts");

const FUNCTIONS = new Set([
  "bookAndMint",
  "quote",
  "seatPrice",
  "seatExists",
  "isSeatAvailable",
  "getSeatAvailability",
  "getBoardingPass",
  "tokenURI",
]);
const EVENTS = new Set(["BoardingPassMinted"]);

type AbiItem = {
  type: string;
  name?: string;
  inputs?: unknown[];
  [key: string]: unknown;
};

function itemKey(item: AbiItem): string {
  return JSON.stringify({
    type: item.type,
    name: item.name ?? "",
    inputs: item.inputs ?? [],
  });
}

function loadArtifactAbi(): AbiItem[] {
  if (!existsSync(ARTIFACT)) {
    throw new Error(
      `Missing ${ARTIFACT}. Run \`pnpm contracts:build\` first.`,
    );
  }
  const artifact = JSON.parse(readFileSync(ARTIFACT, "utf8")) as {
    abi?: unknown;
  };
  if (!Array.isArray(artifact.abi)) {
    throw new Error("BoardingPass artifact has no abi array");
  }
  return artifact.abi as AbiItem[];
}

function selectAbi(abi: AbiItem[]): AbiItem[] {
  const seen = new Set<string>();
  const selected: AbiItem[] = [];
  for (const item of abi) {
    const keep =
      item.type === "error" ||
      (item.type === "function" && item.name !== undefined && FUNCTIONS.has(item.name)) ||
      (item.type === "event" && item.name !== undefined && EVENTS.has(item.name));
    if (!keep) {
      continue;
    }
    const key = itemKey(item);
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    selected.push(item);
  }
  selected.sort((a, b) => {
    const typeOrder = a.type.localeCompare(b.type);
    if (typeOrder !== 0) {
      return typeOrder;
    }
    return (a.name ?? "").localeCompare(b.name ?? "");
  });
  return selected;
}

function render(abi: AbiItem[]): string {
  const json = JSON.stringify(abi, null, 2);
  return `/* Generated by scripts/sync-abi.ts — do not edit by hand. */
import type { Abi } from "viem";

export const boardingPassAbi = ${json} as const satisfies Abi;

export type BoardingPassAbi = typeof boardingPassAbi;
`;
}

const selected = selectAbi(loadArtifactAbi());
for (const name of FUNCTIONS) {
  if (!selected.some((item) => item.type === "function" && item.name === name)) {
    throw new Error(`ABI sync missing function ${name}`);
  }
}
if (!selected.some((item) => item.type === "event" && item.name === "BoardingPassMinted")) {
  throw new Error("ABI sync missing BoardingPassMinted");
}
if (!selected.some((item) => item.type === "error")) {
  throw new Error("ABI sync missing custom errors");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, render(selected), "utf8");
console.log(`Wrote ${selected.length} ABI items to ${OUT}`);
